config/routes.rb
Rails.application.routes.draw do
  root 'users#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  resources :users, only: [:new, :create, :show] do
    resources :friends, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :messages, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :friends, through: :messages
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]
  before_action :require_logout, only: [:home, :new, :create]

# root for login / signup
  def home
  end

# GET /users
# renders the sign up form
  def new
    @user = User.new
  end

# POST /users
# creates an account for the user and logs them in if given valid info
# redirects to sign up page with flash message if not
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    elsif @user.errors.full_messages.present?
      flash[:message] = @user.errors.full_messages.first
      redirect_to new_user_path
    else
      flash[:message] = "invalid information"
      redirect_to new_user_path
    end
  end

# GET /users/:id
# renders the dashboard for existing users
  def show
    @user = User.find_by(id: params[:id])

    if @user.id == current_user.id
      @message = @user.messages.build
      @friends = current_user.friends.distinct
      render layout: "dashboard"
    else
      redirect_to user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_cards.erb
<% current_user.friends.recently_added.distinct.each do |friend| %>
  <div class="card">
    <h3><%= friend.name %></h3>
    <p>📬 <%= friend.email %></p>
    <p>☎️ <%= friend.phone %></p>
    <h4><%= link_to "Edit", edit_user_friend_path(current_user, friend) %></h4>
  </div>
<% end %>

app/views/users/_first-wuphf.erb
<%= form_tag messages_path, method: "post" do %>
  <%= label_tag "", "Friend's Name" %><br>
  <%= text_field_tag :name, '', required: true, autocomplete: "disabled", placeholder: "John Legend", autofocus: true %><br><br>

  <%= label_tag "", "Their Email" %><br>
  <%= email_field_tag :email, '', required: true, autocomplete: "disabled", placeholder: "johnlegend@mac.com" %><br><br>

  <%= label_tag "", "Their Phone Number" %><br>
  <%= telephone_field_tag :phone, '', required: true, autocomplete: "disabled", placeholder: "3102229999" %><br><br>

  <%= label_tag "Message" %><br>
  <%= text_area_tag :content, '', required: true, placeholder: "You should've sent me a WUPHF..." %><br>

  <%= submit_tag "Send first WUPHF!" %><br>
<% end %>

<p><%= flash[:message] %><p>

app/views/users/_form.erb
<%= form_for @user do |f| %>
  <%= f.label "", "Full Name" %><br>
  <%= f.text_field :name, required: true %><br><br>

  <%= f.label "", "Email Address" %><br>
  <%= f.email_field :email, required: true %><br><br>

  <%= f.label "Password"%><br>
  <%= f.password_field :password, required: true %><br><br>

  <%= f.label "", "Password Confirmation"%><br>
  <%= f.password_field :password_confirmation, required: true %><br><br>

  <%= f.submit "Create Account" %><br><br>
<% end %>

<p><%= flash[:message] %></p>

app/views/users/_message.erb
<%= form_for @message do |f| %>
  <%= f.label "Recipient" %><br>
  <%= f.collection_select :friend_id, @friends, :id, :name, include_blank: true, required: true %><br><br>

  <%= f.label "Message" %><br>
  <%= f.text_area :content, required: true, placeholder: "You should've sent me a WUPHF..." %><br>

  <%= f.submit "Send WUPHF!" %><br>
<% end %>

<p><%= flash[:message] %><p>

app/views/users/home.erb
<div class="grid-signin">
  <nav>
    <div><a href="/">WUPHF</a></div>
  </nav>

  <section class="login">
    <div class="login-form">
      <%= button_to 'Sign Up', new_user_path, method: :get %><br>
      <%= button_to 'Log In', login_path, method: :get %>
      <p>__</p><br>
      <%= button_to 'Sign on with Google', '/auth/google_oauth2' %>
    </div>
  </section>

  <section class="filler">
    <div><%= inline_svg_tag "dog.svg" %></div>
  </section>

</div>

app/views/users/new.erb
<div class="grid-signin">
  <nav>
    <div><a href="/">WUPHF</a></div>
  </nav>

  <section class="login">
    <div class="login-form">
      <%= render 'form' %>
    </div>
  </section>

  <section class="filler">
    <div>
      <h4>I wish there was a way that I could do everything all at once,
        and I could just be like this little dog going, ‘Ruff! Ruff! Ruff! Ruff! Ruff!'
      </h4>
      <p>- Kelly Kapoor</p>
    </div>
  </section>

</div>

app/views/users/show.erb
<div class="dashboard">
  <nav>
    <div><%= link_to "WUPHF", user_path(current_user) %></div>
  </nav>

  <div class="logout"><%= link_to "Logout", logout_path, method: :post %></div>

  <section class="msg-container">
    <div class="msg-form">
      <% if current_user.friends.present? %>
        <%= render 'message' %>
      <% else %>
        <%= render 'first-wuphf' %>
      <% end %>
    </div>
  </section>

  <section class="friend-container">
    <div class="empty">
      <%= link_to "+ Add Friend", new_user_friend_path(current_user) %><br>
    </div>
    <%= render 'cards' %>
  </section>

</div>